create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    created_at timestamp with time zone not null,
    constraint uk_users_email unique (email)
);

create table products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    quantity integer not null,
    manufacture_date date not null,
    expiration_date date not null,
    status varchar(32) not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    constraint chk_products_status
        check (status in ('OK', 'NEAR_EXPIRATION', 'EXPIRED')),
    constraint fk_products_user
        foreign key (user_id) references users (id)
);

create table shopping_list_items (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    quantity integer not null,
    checked boolean not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    constraint fk_shopping_list_items_user
        foreign key (user_id) references users (id)
);

create table notification_logs (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    source_module varchar(32) not null,
    source_id bigint not null,
    source_label varchar(255) not null,
    source_date date not null,
    product_id bigint,
    type varchar(32) not null,
    event_date date not null,
    created_at timestamp with time zone not null,
    constraint chk_notification_logs_source_module
        check (source_module in ('PRODUCT', 'AGENDA', 'HOUSE_BILL')),
    constraint chk_notification_logs_type
        check (type in ('EXPIRED', 'NEAR_EXPIRATION')),
    constraint fk_notification_logs_user
        foreign key (user_id) references users (id),
    constraint fk_notification_logs_product
        foreign key (product_id) references products (id)
);

create table agenda_events (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(1000),
    start_at timestamp(6) not null,
    end_at timestamp(6) not null,
    status varchar(32) not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    constraint chk_agenda_events_status
        check (status in ('SCHEDULED', 'COMPLETED', 'CANCELED')),
    constraint fk_agenda_events_user
        foreign key (user_id) references users (id)
);

create table house_bills (
    id bigint generated by default as identity primary key,
    description varchar(255) not null,
    amount numeric(19, 2) not null,
    due_date date not null,
    category varchar(120),
    paid_at date,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    constraint fk_house_bills_user
        foreign key (user_id) references users (id)
);
