create table catalog_products (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    normalized_name varchar(255) not null,
    brand varchar(255),
    category varchar(255),
    barcode varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_catalog_products_normalized_name unique (normalized_name)
);
